# Generated by Django 6.0.1 on 2026-01-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_source_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_carried_forward',
        ),
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='task',
            name='source_task',
        ),
        migrations.AddField(
            model_name='day',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
